# Generated by Django 5.0 on 2023-12-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='transactions',
        ),
    ]
